 version: '3.3'

 services:
   # Mysql
   db:
     image: mysql:5.7
     environment:
       - MYSQL_ROOT_PASSWORD=123
       - MYSQL_DATABASE=theisbn
     ports:
       - "3306:3306"

   web:
     build: .
     command: ["./run_web.sh"]
     volumes:
       - .:/webapps
     ports:
       - "8000:8000"
     links:
       - db
     depends_on:
       - db
